import User from '../models/User.js';
import Invite from '../models/Invite.js';
import { generateToken } from '../middleware/auth.js';

// @desc    Register a new user
// @route   POST /api/auth/register
// @access  Public
export const register = async (req, res) => {
  try {
    const { name, email, password, company, role, phone, skills } = req.body;

    // Check if user exists
    const userExists = await User.findOne({ email });
    if (userExists) {
      return res.status(400).json({ message: 'User already exists with this email' });
    }

// Create user - employeeId will be generated by the User model's pre-save hook
    const { inviteToken } = req.body;

    // If inviteToken provided, validate it and allow registration
    let invite = null;
    if (inviteToken) {
      invite = await Invite.findOne({ token: inviteToken }).populate('createdBy');
      if (!invite) return res.status(400).json({ message: 'Invalid invite token' });
      if (invite.used) return res.status(400).json({ message: 'Invite token already used' });
      if (invite.expiresAt && invite.expiresAt < new Date()) return res.status(400).json({ message: 'Invite token expired' });
    }

    // Guard: allow open self-registration only when explicitly enabled
    const allowSelfRegister = (process.env.ALLOW_SELF_REGISTER === 'true') || (process.env.NODE_ENV === 'development');

    if (!invite && !allowSelfRegister) {
      return res.status(403).json({ message: 'Self-registration is disabled. Please use an invite.' });
    }

    // Decide final role and skills
    const finalRole = invite ? (invite.role || role || 'Employee') : (role || (process.env.ALLOW_SELF_ADMIN === 'true' ? 'Admin' : 'Employee'));
    const finalIsAdmin = invite ? (finalRole === 'Admin') : ((process.env.ALLOW_SELF_ADMIN === 'true') || (process.env.NODE_ENV === 'development'));

    // Determine skills: prefer request body, else invite's skills
    const finalSkills = (skills && Array.isArray(skills) && skills.length > 0) ? skills : (invite ? invite.skills : []);
    if (!finalSkills || finalSkills.length === 0) {
      return res.status(400).json({ message: 'Please provide at least one skill during registration' });
    }

    const user = await User.create({
      name,
      email,
      password,
      phone: phone || '',
      company: invite ? (invite.createdBy?.company || 'ProManage Inc.') : (company || 'ProManage Inc.'),
      role: finalRole,
      isAdmin: finalIsAdmin,
      skills: finalSkills,
      avatar: ''
    });

    // Mark invite used after successful creation
    if (invite) {
      invite.used = true;
      await invite.save();
    }

    if (user) {
      res.status(201).json({
        _id: user._id,
        name: user.name,
        email: user.email,
        employeeId: user.employeeId,
        role: user.role,
        isAdmin: user.isAdmin,
        avatar: user.avatar,
        phone: user.phone,
        company: user.company,
        token: generateToken(user._id)
      });
    }
  } catch (error) {
    console.error('Registration Error:', error);
    res.status(500).json({ message: error.message || 'Server error during registration' });
  }
};

// @desc    Login user
// @route   POST /api/auth/login
// @access  Public
export const login = async (req, res) => {
  try {
    const { email, password, employeeId } = req.body;

    // Find user by email
    const user = await User.findOne({ email }).select('+password');

    console.log(`[DEBUG] Login attempt for email: ${email}`);

    if (!user) {
      console.log(`[DEBUG] User not found for email: ${email}`);
      return res.status(401).json({ message: 'Invalid credentials' });
    }

    // Check if employeeId matches (required for this app)
    console.log(`[DEBUG] Comparing EmployeeID: Sent='${employeeId}', DB='${user.employeeId}'`);
    if (user.employeeId !== employeeId) {
      console.log(`[DEBUG] EmployeeID mismatch`);
      return res.status(401).json({ message: 'Invalid credentials' });
    }

    // Check if password matches
    const isMatch = await user.matchPassword(password);
    console.log(`[DEBUG] Password match result: ${isMatch}`);

    if (!isMatch) {
      return res.status(401).json({ message: 'Invalid credentials' });
    }

    res.json({
      _id: user._id,
      name: user.name,
      email: user.email,
      employeeId: user.employeeId,
      role: user.role,
      isAdmin: user.isAdmin,
      avatar: user.avatar,
      phone: user.phone,
      location: user.location,
      company: user.company,
      token: generateToken(user._id)
    });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @desc    Get current logged in user
// @route   GET /api/auth/me
// @access  Private
export const getMe = async (req, res) => {
  try {
    const user = await User.findById(req.user._id);
    res.json(user);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @desc    Logout user
// @route   POST /api/auth/logout
// @access  Private
export const logout = async (req, res) => {
  res.json({ message: 'Logged out successfully' });
};
